"""baseline

Revision ID: 36c6c9f06d27
Revises: 
Create Date: 2026-09-17 20:12:01.168782

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '36c6c9f06d27'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
